// Words or expressions from Lorraine
export const words = [
  "clanche",
  "flo",
  "touiller",
  "trisser",
  // Food
  "beignet",
  "bergamote",
  "madeleine",
  "migaine",
  "mirabelle",
  "munster",
  "pâté",
  "potée",
  "quiche",
  "schneck",
  // Geography
  "Bar-le-Duc",
  "Champigneulles",
  "Commercy",
  "Épinal",
  "Forbach",
  "Gérardmer",
  "Liverdun",
  "Lunéville",
  "Metz",
  "Montigny-lès-Metz",
  "Nancy",
  "Pont-à-Mousson",
  "Saint-Avold",
  "Saint-Dié-des-Vosges",
  "Sarreguemines",
  "Thionville",
  "Vandœuvre-lès-Nancy",
  "Verdun",
  "Meurthe-et-Moselle",
  "Meuse",
  "Moselle",
  "Vosges",
  // Famous people
  "Saint-Nicolas",
];
