// Words or expressions from Lorraine
export const words = [
  "clanche",
  "flots",
  "touiller",
  "trisser",
  // Food
  "baba",
  "beignet",
  "bergamote",
  "lard",
  "macaron",
  "madeleine",
  "migaine",
  "mirabelle",
  "munster",
  "pâté",
  "potée",
  "quetsche",
  "quiche",
  "schneck",
  // Geography
  "Baccarat",
  "Bar-le-Duc",
  "Champigneulles",
  "Commercy",
  "Épinal",
  "Forbach",
  "Gérardmer",
  "Liverdun",
  "Lunéville",
  "Metz",
  "Montigny-lès-Metz",
  "Munster",
  "Nancy",
  "Pont-à-Mousson",
  "Saint-Avold",
  "Saint-Dié-des-Vosges",
  "Sarreguemines",
  "Thionville",
  "Toul",
  "Vandœuvre-lès-Nancy",
  "Verdun",
  "Meurthe-et-Moselle",
  "Meuse",
  "Moselle",
  "Vosges",
  // Famous people
  "Saint-Nicolas",
];
